/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e75197f06e8563f32296087
*
* You will get 10% discount for each one of your friends
* 
*/
// Import Libraries
import { Component, OnInit } from '@angular/core';
import { Location } from '@angular/common';
import { ActivatedRoute } from '@angular/router';
// Import Services
import { CategoriaService } from '../../services/categoria.service';
import { ProdutoService } from '../../services/produto.service';
// Import Models
import { Categoria } from '../../domain/marktplace_db/categoria';
import { Produto } from '../../domain/marktplace_db/produto';

// START - USED SERVICES
/**
* CategoriaService.create
*	@description CRUD ACTION create
*
* CategoriaService.update
*	@description CRUD ACTION update
*	@param ObjectId id Id
*
* CategoriaService.get
*	@description CRUD ACTION get
*	@param ObjectId id Id resource
*
* ProdutoService.findBy_categoria
*	@description CRUD ACTION findBy_categoria
*	@param Objectid key Id of model to search for
*
*/
// END - USED SERVICES

/**
 * This component allows to edit a Categoria
 */
@Component({
    selector: 'app-categoria-edit',
    templateUrl: 'categoria-edit.component.html',
    styleUrls: ['categoria-edit.component.css']
})
export class CategoriaEditComponent implements OnInit {
    item: Categoria;
    
    externalProduto__categoria: Produto[];
    model: Categoria;
    formValid: Boolean;

    constructor(
    private categoriaService: CategoriaService,
    private produtoService: ProdutoService,
    private route: ActivatedRoute,
    private location: Location) {
        // Init item
        this.item = new Categoria();
        this.externalProduto__categoria = [];
    }

    /**
     * Init
     */
    ngOnInit() {
        this.route.params.subscribe(param => {
            const id: string = param['id'];
            if (id !== 'new') {
                this.categoriaService.get(id).subscribe(item => this.item = item);
                this.produtoService.findBy_categoria(id).subscribe(list => this.externalProduto__categoria = list);
            }
            // Get relations
        });
    }


    /**
     * Save Categoria
     *
     * @param {boolean} formValid Form validity check
     * @param Categoria item Categoria to save
     */
    save(formValid: boolean, item: Categoria): void {
        this.formValid = formValid;
        if (formValid) {
            if (item._id) {
                this.categoriaService.update(item).subscribe(data => this.goBack());
            } else {
                this.categoriaService.create(item).subscribe(data => this.goBack());
            } 
        }
    }

    /**
     * Go Back
     */
    goBack(): void {
        this.location.back();
    }


}



